/**************************************************
     * //File Name: ListViewControllerTest
     * //Created On: 29/07/2021
     * //Created By: Bharathi
     * =======================================
     * Modification Log (Name - Change Summary – Initial) :
*********************************************************************/
@isTest
public class ListViewControllerTest {
	@isTest
    public static void testMethod1(){
        ListViewController.getListValues('Account');
    }
}